
name: Synopsys Security Testing

on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
     MAC_BRIDGE_URL: "https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-bridge/0.1.244/synopsys-bridge-0.1.244-macosx.zip"
     LINUX_BRIDGE_URL: "https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-bridge/0.1.244/synopsys-bridge-0.1.244-linux64.zip"
     WINDOWS_BRIDGE_URL: "https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-bridge/0.1.244/synopsys-bridge-0.1.244-win64.zip"
     TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
      - uses: actions/checkout@v3
      - name: Use synopsys unified-action - blackduck-detect
       # Use the action defined in this repository
      - name: Synopsys Action
        uses: synopsys-sig/synopsys-action@v1.2.0
        with:
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN_NEW }}
          bridge_download_url: ${{ env.LINUX_BRIDGE_URL }}
          blackduck_scan_failure_severities : "[\"BLOCKER\", \"CRITICAL\", \"MAJOR\"]"
          #blackduck_automation_fixpr: true
          #bridge_download_url: "https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/synopsys-action/0.1.192/ci-package-0.1.192-linux64.zip"
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB}}
          include_diagnostics: true
          diagnostics_retention_days: 90

          
